// Lou Magazine - Featured AI Articles
export const featuredArticles = [
  {
    _id: "art-ai-1",
    _type: "article",
    title: "The Great AI Consolidation",
    slug: { current: "ai-consolidation" },
    excerpt: "The dream of democratized AI is colliding with trillion-dollar reality.",
    body: "It was supposed to be a fair fight. The AI landscape is consolidating rapidly. OpenAI dominates with GPT-5. Anthropic leads on safety. Google leverages data. Meta pushes open-source.",
    category: { _id: "cat-ai", name: "AI & Tech", slug: { current: "ai-tech" }, color: "#2563eb" },
    author: { _id: "author-lou", name: "Lou Editorial" },
    featured: true,
    publishedAt: "2026-03-03T10:00:00Z",
    readTime: 8,
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
  },
  {
    _id: "art-ai-2",
    _type: "article",
    title: "AI That Reasons Like Humans",
    slug: { current: "ai-reasoning" },
    excerpt: "New AI systems solve complex math problems that once required human intelligence.",
    body: "For years, AI excelled at patterns but struggled with thinking. New models can think step-by-step. They solve IMO-level math, write bug-free code, reason through physics.",
    category: { _id: "cat-ai", name: "AI & Tech", slug: { current: "ai-tech" }, color: "#2563eb" },
    author: { _id: "author-lou", name: "Lou Editorial" },
    featured: true,
    publishedAt: "2026-03-02T10:00:00Z",
    readTime: 9,
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1e40af 100%)",
  },
  {
    _id: "art-ai-3",
    _type: "article",
    title: "The Copyright Wars Are Just Beginning",
    slug: { current: "copyright-wars" },
    excerpt: "Artists fighting back against AI companies that trained on their work without permission.",
    body: "Sarah Chen discovered her art trained AI without consent. No permission. No payment. Major lawsuits filed against OpenAI, Google, Meta, Microsoft.",
    category: { _id: "cat-ai", name: "AI & Tech", slug: { current: "ai-tech" }, color: "#2563eb" },
    author: { _id: "author-lou", name: "Lou Editorial" },
    featured: false,
    publishedAt: "2026-03-01T10:00:00Z",
    readTime: 7,
    gradient: "linear-gradient(135deg, #2563eb 0%, #0f766e 100%)",
  },
  {
    _id: "art-ai-4",
    _type: "article",
    title: "Multimodal AI Gets Real",
    slug: { current: "multimodal-ai" },
    excerpt: "AI that understands text, images, video, and sound together.",
    body: "Most AI is siloed. Multimodal AI understands everything together. It watches videos, understands context, sees images. This opens new worlds in medicine, manufacturing.",
    category: { _id: "cat-ai", name: "AI & Tech", slug: { current: "ai-tech" }, color: "#2563eb" },
    author: { _id: "author-lou", name: "Lou Editorial" },
    featured: true,
    publishedAt: "2026-02-28T10:00:00Z",
    readTime: 8,
    gradient: "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
  },
  {
    _id: "art-ai-5",
    _type: "article",
    title: "The AI Bubble - Hype or Revolution?",
    slug: { current: "ai-bubble" },
    excerpt: "Billions spent on AI. Returns unclear. Bubble or Industrial Revolution?",
    body: "Everyone's building AI. VCs throw billions at startups. Valuations are insane. This is textbook bubble behavior. BUT AI actually works. Many startups will fail, but technology keeps accelerating.",
    category: { _id: "cat-ai", name: "AI & Tech", slug: { current: "ai-tech" }, color: "#2563eb" },
    author: { _id: "author-lou", name: "Lou Editorial" },
    featured: false,
    publishedAt: "2026-02-27T10:00:00Z",
    readTime: 9,
    gradient: "linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%)",
  },
];
